"""empty message

Revision ID: 2d30c0a29580
Revises: 82f159af7de7
Create Date: 2024-10-12 15:43:09.120054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d30c0a29580'
down_revision = '82f159af7de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form_items', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
