"""empty message

Revision ID: ac51e140944e
Revises: 938820fd6cf8
Create Date: 2024-09-28 21:28:12.292823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac51e140944e'
down_revision = '938820fd6cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_team_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user_teams', ['user_team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_form_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_team_id')

    # ### end Alembic commands ###
